x-app-defaults: &app-defaults
  restart: always
  env_file:
    - .env
  volumes:
    - ${DATA_DIR}/podify/storage:/storage

  depends_on:
    - db
    - redis

services:
  web:
    <<: *app-defaults
    image: maxhollmann/podify:latest
    command: start-server
    ports:
      - 3000:3000
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.podify.rule=Host(`podify.${DOMAIN}`)"
      - "traefik.http.routers.podify.entrypoints=https"
      - "traefik.http.routers.podify.tls=true"
      - "traefik.http.routers.podify.service=podify-media-server@file"
      - "traefik.http.routers.podify.middlewares=jellyfin-mw"

      ## HTTP Service
      - "traefik.http.services.podify.loadBalancer.server.port=3000"
      - "traefik.http.services.podify.loadBalancer.passHostHeader=true"

      ### REDIRECT TO GITHUB ### Usefull for redirecting to github page easily
      # add if podify.webninja.me/github is called, it will redirect to the github page
      - "traefik.http.routers.podify-webninja.rule=Host(`podify.${DOMAIN}`) && Path(`/github`)"
      - "traefik.http.routers.podify-webninja.entrypoints=https"
      - "traefik.http.routers.podify-webninja.middlewares=redirect-to-github-podify@file"
      - "traefik.http.routers.podify-webninja.tls=true"
      # set priority to 1 so it will be checked first
      - "traefik.http.routers.podify-webninja.priority=100"
      # define service for the redirect
      - "traefik.http.routers.podify-webninja.service=podify-webninja"
      - "traefik.http.services.podify-webninja.loadbalancer.server.port=3000"

  worker:
    <<: *app-defaults
    image: maxhollmann/podify:latest
    command: start-worker
    env_file:
      - .env

  db:
    image: postgres:12.3
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

  redis:
    image: redis:6
    restart: always

volumes:
  pgdata:
  storage: