services:
  bytestash:
    container_name: bytestash
    image: "ghcr.io/jordan-dalby/bytestash:latest"
    restart: always
    volumes:
      - ${DATA_DIR}/bytestash:/data/snippets
    # ports:
    #   - "5000:5000"
    env_file: .env
    networks:
      - traefik_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.bytestash.entrypoints=https
      - traefik.http.routers.bytestash.rule=Host(`bytestash.webninja.me`)
      - traefik.http.services.bytestash.loadbalancer.server.port=5000
      - traefik.http.routers.bytestash.tls=true
      - traefik.http.routers.bytestash.middlewares=chain-google-oauth@file

  web:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/hoarder/hoarder:/data
    # ports:
    #   - 3000:3000
    env_file:
      - .env
    networks:
      - traefik_network
      - hoarder_network
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      # OPENAI_API_KEY: ...
      DATA_DIR: /data
    labels:
      - traefik.enable=true
      - traefik.http.routers.hoarder.entrypoints=https
      - traefik.http.routers.hoarder.rule=Host(`hoarder.webninja.me`)
      - traefik.http.services.hoarder.loadbalancer.server.port=3000
      - traefik.http.routers.hoarder.tls=true
      - traefik.http.routers.hoarder.middlewares=chain-google-oauth@file
      # use traefik_network to connect to traefik
      - traefik.docker.network=traefik_network
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    networks:
      - hoarder_network
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    restart: unless-stopped
    networks:
      - hoarder_network
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - ${DATA_DIR}/hoarder/meilisearch:/data

networks:
  traefik_network:
    external: true
  hoarder_network:
    external: true
