######################################################
#
# Downloaders
#
# Services: qbittorrent, flaresolverr
#
######################################################

services:
  # gluetun VPN
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    env_file: .env
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      ## Oauth2 authentication
      - "traefik.http.routers.gluetun-qbittorrent.rule=Host(`qbittorrent.${DOMAIN}`)"
      - "traefik.http.routers.gluetun-qbittorrent.entrypoints=https"
      - "traefik.http.routers.gluetun-qbittorrent.tls=true"
      - "traefik.http.routers.gluetun-qbittorrent.middlewares=chain-tinyauth-oauth@file"
      - "traefik.http.routers.gluetun-qbittorrent.service=gluetun-qbittorrent"
      - "traefik.http.services.gluetun-qbittorrent.loadbalancer.server.port=8080"
      # ## No authentication access
      # - "traefik.http.routers.gluetun-qbittorrent-no-auth.rule=Host(`q-no-auth.${DOMAIN}`)"
      # - "traefik.http.routers.gluetun-qbittorrent-no-auth.entrypoints=https"
      # - "traefik.http.routers.gluetun-qbittorrent-no-auth.tls=true"
      # - "traefik.http.routers.gluetun-qbittorrent-no-auth.middlewares=chain-no-auth@file"
      # - "traefik.http.routers.gluetun-qbittorrent-no-auth.service=gluetun-qbittorrent-no-auth"
      # - "traefik.http.services.gluetun-qbittorrent-no-auth.loadbalancer.server.port=8080"
      # # make this high priority
      - "traefik.http.routers.gluetun-qbittorrent.priority=10"

    depends_on:
      mount-check:
        condition: service_healthy

  # qBittorrent: Torrent client
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:libtorrentv1
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TP_THEME=nord
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    env_file: .env
    volumes:
      - ${DATA_DIR}/media-server/qbittorrent:/config
      - ${MEDIA_DIR}/torrents:/data/torrents
      # timezone
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
      mount-check:
        condition: service_healthy

  iqbit:
    image: pratikngupta/iqbit:latest
    container_name: iqbit
    restart: unless-stopped
    networks:
      - traefik_network
    # ports:
    #   - 8081:8081
    environment:
      - QBIT_HOST=https://qbittorrent.techsanctuary.me
      - STANDALONE_SERVER_PORT=8081

    labels:
      - "traefik.enable=true"
      ## Internal access
      - "traefik.http.routers.mobile-qbittorrent.rule=Host(`iqbit.techsanctuary.me`)"
      - "traefik.http.routers.mobile-qbittorrent.entrypoints=https"
      - "traefik.http.services.mobile-qbittorrent.loadbalancer.server.port=8081"
      ## add google oauth
      - "traefik.http.routers.mobile-qbittorrent.middlewares=chain-tinyauth-oauth@file"
      ## theme file for mobile-qbittorrent
      # enable tls
      - "traefik.http.routers.mobile-qbittorrent.tls=true"
      - "dev.dozzle.group=Smart Media"
    depends_on:
      mount-check:
        condition: service_healthy

  # flaresolverr: proxy to resolve cloudflare protected sites
  byparr:
    container_name: byparr
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped
    image: ghcr.io/thephaseless/byparr:latest
    networks:
      - traefik_network
    labels:
      - "dev.dozzle.group=Smart Media"
    depends_on:
      mount-check:
        condition: service_healthy

  feishin:
    container_name: feishin
    image: "ghcr.io/jeffvli/feishin:latest"
    networks:
      - traefik_network
    environment:
      # - SERVER_NAME=navidrome # pre defined server name
      # - SERVER_LOCK=true # When true AND name/type/url are set, only username/password can be toggled
      # - SERVER_TYPE=navidrome # navidrome also works
      # - SERVER_URL=http://navidrome:4533 # http://address:port
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Los_Angeles
    # ports:
    #   - 9180:9180
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.feishin.rule=Host(`feishin.${DOMAIN}`)"
      - "traefik.http.routers.feishin.entrypoints=https"
      - "traefik.http.services.feishin.loadbalancer.server.port=9180"
      - "traefik.http.routers.feishin.middlewares=chain-tinyauth-oauth@file"
      - "traefik.http.routers.feishin.tls=true"
    depends_on:
      mount-check:
        condition: service_healthy

networks:
  traefik_network:
    external: true
### IMPORTANT ###
# To use iQbit UI: `/config/iQbit/release`
# to use vuetorrent UI: `/vuetorrent`
