######################################################
#
# Helper
#
# Services: Tautili, Kometa, Recycler
#
######################################################

services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - DATA_DIR${DATA_DIR}
    volumes:
      - ${DATA_DIR}/tautulli/config:/config
      # timezone
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth Bypass
      - "traefik.http.routers.tautulli-rtr-bypass.entrypoints=https"
      - "traefik.http.routers.tautulli-rtr-bypass.rule=Host(`tautulli.$DOMAIN`) && Header(`traefik-auth-bypass-key`, `$TRAEFIK_AUTH_BYPASS_KEY`)" # Bypass Auth for LunaSea on iOS
      - "traefik.http.routers.tautulli-rtr-bypass.priority=100"
      ## HTTP Routers Auth
      - "traefik.http.routers.tautulli-rtr.entrypoints=https"
      - "traefik.http.routers.tautulli-rtr.rule=Host(`tautulli.$DOMAIN`)"
      - "traefik.http.routers.tautulli-rtr.priority=99"
      ## Enable tls
      - "traefik.http.routers.tautulli-rtr.tls=true"
      - "traefik.http.routers.tautulli-rtr-bypass.tls=true"
      ## Middleware
      - "traefik.http.routers.tautulli-rtr-bypass.middlewares=chain-no-auth@file"
      - "traefik.http.routers.tautulli-rtr.middlewares=chain-github-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.tautulli-rtr.service=tautulli-svc"
      - "traefik.http.routers.tautulli-rtr-bypass.service=tautulli-svc"
      - "traefik.http.services.tautulli-svc.loadbalancer.server.port=8181"
      - "dev.dozzle.group=Smart Media"

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    user: 1000:1000
    env_file: .env
    networks:
      - traefik_network
    volumes:
      - ${DATA_DIR}/recyclarr:/config
      # timezone
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "dev.dozzle.group=Smart Media"

#  kometa:
#    image: kometateam/kometa
#    container_name: kometa
#    volumes:
#      - ${DATA_DIR}/kometa/config:/config
#    restart: unless-stopped
#    networks:
#      - traefik_network
#    command: --run  kometa:
#    image: kometateam/kometa
#    container_name: kometa
#    volumes:
#      - ${DATA_DIR}/kometa/config:/config
#    restart: unless-stopped
#    networks:
#      - traefik_network
#    command: --run

networks:
  traefik_network:
    external: true
