######################################################
#
# Media Server
#
# Services: Plex, Jellyfin
#
######################################################

services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - HOSTNAME=plex.${DOMAIN}
      - APPLE_DIR=/mnt/storage/photo/apple
      - GOOGLE_DIR=/mnt/storage/photo/google
      - ORIGINAL_DIR=/mnt/storage/photo/original-archive
    env_file: .env
    volumes:
      - ${DATA_DIR}/plex:/config
      - ${MEDIA_DIR}/media:/movies
      # timezone
      - /etc/localtime:/etc/localtime:ro
      - /mnt/storage/photo/apple:/mnt/photo/apple
      - /mnt/storage/photo/google:/mnt/photo/google
      - /mnt/storage/photo/original-archive:/mnt/photo/original-archive
      - ${DRIVE_POOL}:/DRIVE_POOL
    tmpfs:
      - /transcode:size=15G
    network_mode: host
    privileged: true # libusb_init failed
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`playninja.${DOMAIN}`)"
      - "traefik.http.routers.plex.entrypoints=https"
      - "traefik.http.routers.plex.tls=true"
      - "traefik.http.routers.plex.service=plex-media-server@file"
      - "traefik.http.routers.plex.middlewares=secure-media-mw@file"

      ## HTTP Service
      - "traefik.http.services.plex.loadBalancer.server.port=32400"
      - "traefik.http.services.plex.loadBalancer.passHostHeader=true"
      - "dev.dozzle.group=Smart Media"
    #depends_on:
    #mount-check:
    #condition: service_healthy

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    # Optional - specify the uid and gid you would like Jellyfin to use instead of root
    user: 1000:1000
    group_add:
      - "993" # render
      - "44" # video
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - ${DATA_DIR}/jellyfin/config:/config
      - ${DATA_DIR}/jellyfin/cache:/cache
      - ${MEDIA_DIR}/media:/media
      - ${DRIVE_POOL}:/DRIVE_POOL
    restart: "unless-stopped"
    env_file: .env
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.${DOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN}`)"
      - "traefik.http.routers.jellyfin.entrypoints=https"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.service=jellyfin-svc@file"
      - "traefik.http.routers.jellyfin.middlewares=secure-media-mw@file"
      - "traefik.http.services.jellyfin-svc.loadbalancer.server.port=8096"
      - "dev.dozzle.group=Smart Media"
    devices:
      - /dev/dri:/dev/dri
    # tmpfs:
    #   - /cache/transcodes:size=15G

  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    # user: 1000:1000 # should be owner of volumes
    networks:
      - traefik_network
    # ports:
    #   - "4533:4533"
    restart: unless-stopped
    env_file: .env
    volumes:
      - ${DATA_DIR}/navidrome:/data:rw
      - ${MEDIA_DIR}/media/music:/music:ro
    labels:
      - "traefik.enable=true"
      ## navidrome UI
      - "traefik.http.routers.navidrome-rtr.entrypoints=https"
      - "traefik.http.routers.navidrome-rtr.rule=Host(`navidrome.$DOMAIN`)"
      - "traefik.http.routers.navidrome-rtr.priority=99"
      - "traefik.http.routers.navidrome-rtr.tls=true"
      - "traefik.http.routers.navidrome-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.navidrome-rtr.service=navidrome-svc"
      - "traefik.http.services.navidrome-svc.loadbalancer.server.port=4533"
      ## Redirect to GitHub
      - "traefik.http.routers.navidrome-github.rule=Host(`navidrome.$DOMAIN`) && Path(`/github`)"
      - "traefik.http.routers.navidrome-github.entrypoints=https"
      - "traefik.http.routers.navidrome-github.tls=true"
      - "traefik.http.routers.navidrome-github.priority=100"
      - "traefik.http.routers.navidrome-github.middlewares=redirect-to-github-navidrome@file"
      - "traefik.http.routers.navidrome-github.service=navidrome-github"
      - "traefik.http.services.navidrome-github.loadbalancer.server.port=4533"
    #depends_on:
    #mount-check:
    #condition: service_healthy

  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    # ports:
    #   - 13378:80
    env_file: .env
    volumes:
      - ${MEDIA_DIR}/media:/movies:/audiobooks
      - ${DATA_DIR}/audiobookshelf/config:/config
      - ${DATA_DIR}/audiobookshelf/metadata:/metadata
    environment:
      - TZ=America/Toronto
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.audiobookshelf-rtr.entrypoints=https"
      - "traefik.http.routers.audiobookshelf-rtr.rule=Host(`shelf.$DOMAIN`)"
      - "traefik.http.routers.audiobookshelf-rtr.priority=99"
      - "traefik.http.routers.audiobookshelf-rtr.tls=true"
      - "traefik.http.routers.audiobookshelf-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.audiobookshelf-rtr.service=audiobookshelf-svc"
      - "traefik.http.services.audiobookshelf-svc.loadbalancer.server.port=80"

  tunarr:
    image: chrisbenincasa/tunarr:latest
    container_name: tunarr
    # ports:
    #   - "8000:8000"
    environment:
      - LOG_LEVEL=${TUNARR_LOG_LEVEL:-INFO}
      - TZ=America/Toronto
      - PUID=1000
      - PGID=1000
      - TUNARR_SERVER_ADMIN_MODE=true
      - NVIDIA_VISIBLE_DEVICES=all

    env_file: .env
    volumes:
      - ${DATA_DIR}/tunarr:/config/tunarr
      # mount all the media and drive pool
      - ${MEDIA_DIR}/media:/movies
      - ${DRIVE_POOL}:/DRIVE_POOL

    tmpfs:
      - /transcode:size=15G
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tunarr.rule=Host(`tunarr.${DOMAIN}`)"
      - "traefik.http.routers.tunarr.entrypoints=https"
      - "traefik.http.routers.tunarr.tls=true"

      - "traefik.http.routers.tunarr.service=tunarr"
      - "traefik.http.services.tunarr.loadbalancer.server.port=8000"
      - "traefik.http.services.tunarr.loadBalancer.passHostHeader=true"

      ## Middlewares
      - "traefik.http.routers.tunarr.middlewares=secure-media-mw@file,chain-no-auth@file"

    # pass intel gpu to container
    devices:
      - /dev/dri:/dev/dri
    runtime: nvidia

  threadfin:
    image: fyb3roptik/threadfin:latest
    container_name: threadfin
    restart: unless-stopped
    env_file: .env
    networks:
      - traefik_network
    volumes:
      - ${DATA_DIR}/threadfin/conf:/home/threadfin/conf
      - ${DATA_DIR}/threadfin/temp:/tmp/threadfin
      - ${DATA_DIR}/iptv/public/guide.xml:/home/epg/guide.xml:ro
    environment:
      - TZ=America/Toronto 
      - PUID=1000
      - PGID=1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.threadfin.rule=Host(`threadfin.${DOMAIN}`)"
      - "traefik.http.routers.threadfin.entrypoints=https"
      - "traefik.http.routers.threadfin.tls=true"
      - "traefik.http.services.threadfin.loadbalancer.server.port=34400"
      - "traefik.http.routers.threadfin.middlewares=secure-media-mw@file,chain-no-auth@file"


  epg-grabber:
    image: ghcr.io/iptv-org/epg:master
    container_name: epg-grabber
    user: "1000:1000"
    env_file: .env
    networks:
      - traefik_network
    environment:
      - TZ=America/Toronto
      - CRON_SCHEDULE=0 0 * * * # Runs every night at midnight
    volumes:
      - ${DATA_DIR}/iptv/channels.xml:/epg/channels.xml
      - ${DATA_DIR}/iptv/public:/epg/public
      - ${DATA_DIR}/iptv/api:/mnt/docker/appData/data:ro

    restart: unless-stopped
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.epg.rule=Host(`epg.${DOMAIN}`)"
    #   - "traefik.http.routers.epg.entrypoints=https"
    #   - "traefik.http.routers.epg.tls=true"
    #   - "traefik.http.services.epg.loadbalancer.server.port=3000"
    #   - "traefik.http.routers.epg.middlewares=secure-media-mw@file,chain-no-auth@file"
    dns:
      - 8.8.8.8
      - 1.1.1.1
networks:
  traefik_network:
    external: true
