######################################################
#
# Requester Services
#
# Services: seerr, requestrr
#
######################################################

services:
  seerr:
    image: seerr/seerr:develop
    init: true
    container_name: seerr
    environment:
      - PUID=1000
      - PGID=1000
      - LOG_LEVEL=debug
    env_file: .env
    networks:
      - traefik_network
    volumes:
      - ${DATA_DIR}/media-server/overseerr:/app/config
      # timezone
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth Bypass
      - "traefik.http.routers.seerr-rtr-bypass.entrypoints=https"
      - "traefik.http.routers.seerr-rtr-bypass.rule=Host(`seerr.$DOMAIN`) && Header(`traefik-auth-bypass-key`, `$TRAEFIK_AUTH_BYPASS_KEY`)" # Bypass Auth for LunaSea on iOS
      - "traefik.http.routers.seerr-rtr-bypass.priority=100"
      ## HTTP Routers Auth
      - "traefik.http.routers.seerr-rtr.entrypoints=https"
      - "traefik.http.routers.seerr-rtr.rule=Host(`seerr.$DOMAIN`)"
      - "traefik.http.routers.seerr-rtr.priority=99"
      ## Enable tls
      - "traefik.http.routers.seerr-rtr.tls=true"
      - "traefik.http.routers.seerr-rtr-bypass.tls=true"
      ## Middleware
      - "traefik.http.routers.seerr-rtr-bypass.middlewares=chain-no-auth@file"
      - "traefik.http.routers.seerr-rtr.middlewares=chain-tinyauth-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.seerr-rtr.service=seerr-svc"
      - "traefik.http.routers.seerr-rtr-bypass.service=seerr-svc"
      - "traefik.http.services.seerr-svc.loadbalancer.server.port=5055"

      ### REDIRECT TO GITHUB ### Usefull for redirecting to github page easily
      # add if seerr.techsanctuary.me/github is called, it will redirect to the github page
      - "traefik.http.routers.seerr-techsanctuary.rule=Host(`seerr.${DOMAIN}`) && Path(`/github`)"
      - "traefik.http.routers.seerr-techsanctuary.entrypoints=https"
      - "traefik.http.routers.seerr-techsanctuary.middlewares=redirect-to-github-seerr@file"
      - "traefik.http.routers.seerr-techsanctuary.tls=true"
      # set priority to 1 so it will be checked first
      - "traefik.http.routers.seerr-techsanctuary.priority=100"
      # define service for the redirect
      - "traefik.http.routers.seerr-techsanctuary.service=seerr-techsanctuary"
      - "traefik.http.services.seerr-techsanctuary.loadbalancer.server.port=5055"
      - "dev.dozzle.group=Smart Media"
    #depends_on:
    #mount-check:
    #condition: service_healthy
networks:
  traefik_network:
    external: true
