######################################################
#
# Downloaders
#
# Services: qbittorrent, flaresolverr
#
######################################################

services:
  # qBittorrent: Torrent client
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - DOCKER_MODS=ghcr.io/gabe565/linuxserver-mod-vuetorrent
    env_file: .env
    ports:
      - 8080:8080
    volumes:
      - ${DATA_DIR}/media-server/qbittorrent:/config
      - ${MEDIA_DIR}/torrents:/data/torrents
      # timezone
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      ## Internal access
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.${DOMAIN}`)"
      - "traefik.http.routers.qbittorrent.entrypoints=https"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
      ## add google oauth
      - "traefik.http.routers.qbittorrent.middlewares=chain-github-oauth@file"
      ## theme file for qBittorrent
      # enable tls
      - "traefik.http.routers.qbittorrent.tls=true"
      - "dev.dozzle.group=Smart Media"

  iqbit:
    image: pratikngupta/iqbit:latest
    container_name: iqbit
    restart: unless-stopped
    networks:
      - traefik_network
    # ports:
    #   - 8081:8081
    environment:
      - QBIT_HOST=https://qbittorrent.techsanctuary.me
      - STANDALONE_SERVER_PORT=8081

    labels:
      - "traefik.enable=true"
      ## Internal access
      - "traefik.http.routers.mobile-qbittorrent.rule=Host(`iqbit.techsanctuary.me`)"
      - "traefik.http.routers.mobile-qbittorrent.entrypoints=https"
      - "traefik.http.services.mobile-qbittorrent.loadbalancer.server.port=8081"
      ## add google oauth
      - "traefik.http.routers.mobile-qbittorrent.middlewares=chain-github-oauth@file"
      ## theme file for mobile-qbittorrent
      # enable tls
      - "traefik.http.routers.mobile-qbittorrent.tls=true"
      - "dev.dozzle.group=Smart Media"

  # flaresolverr: proxy to resolve cloudflare protected sites
  flaresolverr:
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped
    image: ghcr.io/flaresolverr/flaresolverr:latest
    networks:
      - traefik_network
    labels:
      - "dev.dozzle.group=Smart Media"

networks:
  traefik_network:
    external: true

### IMPORTANT ###
# To use iQbit UI: `/config/iQbit/release`
# to use vuetorrent UI: `/vuetorrent`
