services:
  samba:
    container_name: samba
    image: crazymax/samba
    network_mode: host
    env_file: .env
    volumes:
      - ${DATA_DIR}/samba:/data
      - ${DRIVE_TWO}:/samba/storage
      - ${DRIVE_ONE}:/samba/movie
      - ${DATA_DIR}:/samba/appData
    environment:
      - "BROWSABLE=yes"
      - SAMBA_LOG_LEVEL=0
    restart: always

  avahi:
    container_name: avahi
    image: ydkn/avahi
    hostname: $HOSTNAME
    network_mode: host
    env_file: .env
    volumes:
      - ${DATA_DIR}/avahi:/etc/avahi/services:ro
    restart: always

  minidlna:
    container_name: minidlna
    network_mode: host
    env_file: .env
    volumes:
      - ${STORAGE_DIR}:/opt/Videos
      - ${STORAGE_DIR}/music:/opt/Music
    image: geekduck/minidlna

networks:
  traefik_network:
    external: true
