version: "3.3"
services:
  portainer-ce:
    container_name: portainer
    restart: unless-stopped
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR}/portainer:/data
    image: portainer/portainer-ee:latest
    networks:
      - traefik_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.entrypoints=https
      - traefik.http.routers.portainer.rule=Host(`portainer.webninja.me`)
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      # enable tls
      - traefik.http.routers.portainer.tls=true
      # enable middleware
      - traefik.http.routers.portainer.middlewares=chain-google-oauth@file

networks:
  traefik_network:
    external: true
