services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    env_file:
      - .env
    environment:
      DOMAIN: "https://vaultwarden.${DOMAIN}" # required when using a reverse proxy; your domain; vaultwarden needs to know it's https to work properly with attachments
      WEBSOCKET_ENABLED: "true"
      SENDS_ALLOWED: "true"
      PASSWORD_ITERATIONS: 700000
      SMTP_TIMEOUT: 15
      EXTENDED_LOGGING: "true"
      TZ: "America/Toronto"
    volumes:
      - ${DATA_DIR}/vaultwarden:/data # the path before the : can be changed
    labels:
      # traefik enable
      - "traefik.enable=true"
      - "traefik.docker.network=vaultwarden_secure_network"

      - "traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.${DOMAIN}`)"
      - "traefik.http.routers.vaultwarden.entrypoints=https"
      - "traefik.http.routers.vaultwarden.priority=1"
      - "traefik.http.routers.vaultwarden.tls=true"
      - "traefik.http.routers.vaultwarden.service=vaultwarden"
      - "traefik.http.routers.vaultwarden.middlewares=chain-no-auth@file"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"

      # add if vaultwarden.webninja.me/github is called, it will redirect to the github page
      - "traefik.http.routers.vaultwarden-webninja.rule=Host(`vaultwarden.${DOMAIN}`) && (Path(`/github`) || Path(`/admin`))"
      - "traefik.http.routers.vaultwarden-webninja.entrypoints=https"
      - "traefik.http.routers.vaultwarden-webninja.middlewares=chain-no-auth@file, redirect-to-github-vaultwarden@file"
      - "traefik.http.routers.vaultwarden-webninja.tls=true"
      - "traefik.http.routers.vaultwarden-webninja.priority=100"
      - "traefik.http.routers.vaultwarden-webninja.service=vaultwarden-webninja"
      - "traefik.http.services.vaultwarden-webninja.loadbalancer.server.port=80"

      # Prevent watchtower from updating this container
      - com.centurylinklabs.watchtower.monitor-only="true"
    networks:
      - vaultwarden_secure_network

  backup:
    image: jmqm/vaultwarden_backup:latest
    container_name: vaultwarden_backup
    network_mode: none
    volumes:
      - ${DATA_DIR}/vaultwarden:/data:ro # Read-only
      - "/home/pratik/Docker/onedrive/data/Vaultwarden (Homelab Upload):/backups"
      - /etc/localtime:/etc/localtime:ro # Container uses date from host.
    environment:
      - DELETE_AFTER=30
      - CRON_TIME=* */24 * * * # Runs at 12:00 AM.
      - UID=1000
      - GID=1000

networks:
  vaultwarden_secure_network:
    external: true
