

services:
    scrypted:
        environment:
            # Scrypted NVR Storage (Part 2 of 3)

            # Uncomment the next line to configure the NVR plugin to store recordings
            # use the /nvr directory within the container. This can also be configured
            # within the plugin manually.
            # The drive or network share will ALSO need to be configured in the volumes
            # section below.
            # - SCRYPTED_NVR_VOLUME=/nvr

            - SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION=${bearere}
            - SCRYPTED_WEBHOOK_UPDATE=http://localhost:10444/v1/update

            # Avahi can be used for network discovery by passing in the host daemon
            # or running the daemon inside the container. Choose one or the other.
            # Uncomment next line to run avahi-daemon inside the container.
            # See volumes and security_opt section below to use the host daemon.
            # - SCRYPTED_DOCKER_AVAHI=true

            # NVIDIA (Part 1 of 4)
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all

        # NVIDIA (Part 2 of 4)
        runtime: nvidia

        # NVIDIA (Part 3 of 4) - Use NVIDIA image, and remove subsequent default image.
        image: ghcr.io/koush/scrypted:nvidia
        env_file: .env
        volumes:
            # NVIDIA (Part 4 of 4)
            - /etc/OpenCL/vendors/nvidia.icd:/etc/OpenCL/vendors/nvidia.icd

            # Default volume for the Scrypted database. Typically should not be changed.
            - /home/pratik/appData/data/scrypted/:/server/volume

        devices: [
            # uncomment the common systems devices to pass
            # them through to docker.

            # all usb devices, such as coral tpu
            # "/dev/bus/usb:/dev/bus/usb",

            # hardware accelerated video decoding, opencl, etc.
            "/dev/dri:/dev/dri"

            # uncomment below as necessary.
            # zwave usb serial device

            # "/dev/ttyACM0:/dev/ttyACM0",

            # coral PCI devices
            # "/dev/apex_0:/dev/apex_0",
            # "/dev/apex_1:/dev/apex_1",
        ]

        container_name: scrypted
        restart: unless-stopped
        network_mode: host

        # logging is noisy and will unnecessarily wear on flash storage.
        # scrypted has per device in memory logging that is preferred.
        # enable the log file if enhanced debugging is necessary.
        logging:
            driver: "none"
            # driver: "json-file"
            # options:
            #     max-size: "10m"
            #     max-file: "10"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.camera.rule=Host(`camera.${DOMAIN}`)"
            - "traefik.http.routers.camera.entrypoints=https"
            - "traefik.http.routers.camera.tls=true"
            - "traefik.http.services.camera.loadbalancer.server.port=10444"
            - "traefik.http.routers.camera.service=camera-server@file"
            ## Middlewares
            # - "traefik.http.routers.camera.middlewares=chain-google-oauth@file"
            - "traefik.http.routers.camera.middlewares=chain-no-auth@file"