services:
  scrypted:
    environment:
      - SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION=${bearere}
      - SCRYPTED_WEBHOOK_UPDATE=http://localhost:10444/v1/update

      # NVIDIA (Part 1 of 4)
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

    # NVIDIA (Part 2 of 4)
    runtime: nvidia

    # NVIDIA (Part 3 of 4) - Use NVIDIA image, and remove subsequent default image.
    image: ghcr.io/koush/scrypted:nvidia
    env_file: .env
    volumes:
      # NVIDIA (Part 4 of 4)
      - /etc/OpenCL/vendors/nvidia.icd:/etc/OpenCL/vendors/nvidia.icd

      # Default volume for the Scrypted database. Typically should not be changed.
      - /mnt/camera/scrypted:/server/volume

      # localtime
      - /etc/localtime:/etc/localtime:ro

    devices: [ "/dev/dri:/dev/dri" ]

    container_name: scrypted
    restart: unless-stopped
    networks:
      - traefik_network
          # ipv4_address: 172.18.0.7
      - camera_internal
          # ipv4_address: 172.21.0.2

    # logging is noisy and will unnecessarily wear on flash storage.
    # scrypted has per device in memory logging that is preferred.
    # enable the log file if enhanced debugging is necessary.
    logging:
      driver: "none"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.scrypted.rule=Host(`scrypted.${DOMAIN}`)"
      - "traefik.http.routers.scrypted.entrypoints=https"
      - "traefik.http.routers.scrypted.tls=true"
      - "traefik.http.services.scrypted.loadbalancer.server.port=11080"
      - "traefik.http.routers.scrypted.middlewares=chain-github-oauth@file"
      - "traefik.docker.network=traefik_network"

networks:
  traefik_network:
    external: true
  #   ipam:
  #     config:
  #       - subnet: 172.18.0.0/24
  #         gateway: 172.18.0.1
  #         auxiliary_addresses:
  #           scrypted: 172.18.0.7
            
  # camera_internal:
  #   external: true
  # #   ipam:
  # #     config:
  # #       - subnet: 172.21.0.0/24
  # #         gateway: 172.21.0.1
  # #         auxiliary_addresses:
  # #           scrypted: 172.21.0.2
