######################################################
#
# Helper
#
# Services: Tautili, Kometa, Recycler
#
######################################################

services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data/tautulli/config:/config
    # timezone 
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    networks:
      - proxy_default
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth Bypass
      - "traefik.http.routers.tautulli-rtr-bypass.entrypoints=https"
      - "traefik.http.routers.tautulli-rtr-bypass.rule=Host(`tautulli.$DOMAIN`) && Header(`traefik-auth-bypass-key`, `$TRAEFIK_AUTH_BYPASS_KEY`)" # Bypass Auth for LunaSea on iOS
      - "traefik.http.routers.tautulli-rtr-bypass.priority=100"
      ## HTTP Routers Auth
      - "traefik.http.routers.tautulli-rtr.entrypoints=https"
      - "traefik.http.routers.tautulli-rtr.rule=Host(`tautulli.$DOMAIN`)"
      - "traefik.http.routers.tautulli-rtr.priority=99"
      ## Enable tls
      - "traefik.http.routers.tautulli-rtr.tls=true"
      - "traefik.http.routers.tautulli-rtr-bypass.tls=true"
      ## Middleware
      - "traefik.http.routers.tautulli-rtr-bypass.middlewares=chain-no-auth@file"
      - "traefik.http.routers.tautulli-rtr.middlewares=chain-google-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.tautulli-rtr.service=tautulli-svc"
      - "traefik.http.routers.tautulli-rtr-bypass.service=tautulli-svc"
      - "traefik.http.services.tautulli-svc.loadbalancer.server.port=8181"

      ## Homepage
      - "homepage.group=Monitoring"
      - "homepage.name=Tautulli"
      - "homepage.icon=tautulli"
      - "homepage.href=https://tautulli.${DOMAIN}/"
      - "homepage.description=Media monitoring"
      - "homepage.color=#FFA500"
      - "homepage.widget.type=tautulli"
      - "homepage.widget.url=http://tautulli:8181"
      - "homepage.widget.key=${TAUTULLI_API_KEY}"

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    user: 1000:1000
    networks:
      - proxy_default
    volumes:
      - ./data/recyclarr:/config
    # timezone 
      - /etc/localtime:/etc/localtime:ro

#  kometa:
#    image: kometateam/kometa
#    container_name: kometa
#    volumes:
#      - ./data/kometa/config:/config
#    restart: unless-stopped
#    networks:
#      - proxy_default
#    command: --run  kometa:
#    image: kometateam/kometa
#    container_name: kometa
#    volumes:
#      - ./data/kometa/config:/config
#    restart: unless-stopped
#    networks:
#      - proxy_default
#    command: --run

networks:
  proxy_default:
    external: true
