######################################################
#
# Downloaders
#
# Services: qbittorrent, flaresolverr
#
######################################################


services:
  # qBittorrent: Torrent client
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - DOCKER_MODS=ghcr.io/gabe565/linuxserver-mod-vuetorrent
    volumes:
      - ./data/qbittorrent:/config
      - ./content/torrents:/data/torrents
    restart: unless-stopped
    networks:
      - proxy_default
    labels:
      - "traefik.enable=true"
      ## Internal access
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.${DOMAIN}`)"
      - "traefik.http.routers.qbittorrent.entrypoints=https"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
      ## add google oauth
      - "traefik.http.routers.qbittorrent.middlewares=chain-google-oauth@file"
      ## theme file for qBittorrent
      # enable tls
      - "traefik.http.routers.qbittorrent.tls=true"

  # flaresolverr: proxy to resolve cloudflare protected sites
  flaresolverr:
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped
    image: ghcr.io/flaresolverr/flaresolverr:latest
    networks:
      - proxy_default

networks:
  proxy_default:
    external: true


### IMPORTANT ###
# To use iQbit UI: `/config/iQbit/release`
# to use vuetorrent UI: `/vuetorrent`