version: "3.8"

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    env_file: .env
    volumes:
      # - ${DATA_DIR}/nextcloud:/mnt/docker-aio-config
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/nextcloud:/mnt/ncdata
    networks:
      - traefik_network
    # ports:
    #   - 8080:8080
    environment:
      - APACHE_PORT=11000
      - NEXTCLOUD_DATADIR=/mnt/ncdata
      - APACHE_IP_BINDING=0.0.0.0
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.entrypoints=https
      - traefik.http.services.nextcloud.loadbalancer.server.scheme=https
      - traefik.http.routers.nextcloud.rule=Host(`nextcloud.techsanctuary.me`)
      - traefik.http.services.nextcloud.loadbalancer.server.port=11000
      # enable tls
      - traefik.http.routers.nextcloud.tls=true
      - "traefik.http.routers.nextcloud.middlewares=chain-no-auth@file"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

networks:
  traefik_network:
    external: true
