version: '3'
services:
  tensorflow:
    runtime: nvidia
    image: tensorflow/tensorflow:latest-gpu-jupyter
    ports:
      - "8888:8888"
    stdin_open: true
    tty: true
    volumes:
      - /data:/path/in/container