version: "3"
services:
  tensorflow-gpu:
    runtime: nvidia
    image: tensorflow/tensorflow:latest-gpu-jupyter
    ports:
      - 8888:8888
    stdin_open: true
    tty: true
    volumes:
      - ./data:/tf
  tensorflow-cpu:
    image: tensorflow/tensorflow:latest-jupyter
    ports:
      - 8889:8888
    stdin_open: true
    tty: true
    volumes:
      - ./data:/tf
networks: {}
