version: "3.3"
  # services:
  #  homepage:
  #    image: ghcr.io/gethomepage/homepage:latest
  #    container_name: homepage
  #    env_file: .env
  #    volumes:
  #      - ./data/homepage:/app/config # Make sure your local config directory exists
  #      - /var/run/docker.sock:/var/run/docker.sock
  #    networks:
  #      - traefik_network
  #    labels:
  #      - "traefik.enable=true"
  #      - "traefik.http.routers.homepage.rule=Host(`homepage.${DOMAIN}`)"
  #      - "traefik.http.routers.homepage.entrypoints=https"
  #      - "traefik.http.routers.homepage.tls=true"
  #      - "traefik.http.services.homepage.loadbalancer.server.port=3000"

networks:
  traefik_network:
    external: true
