http:
  middlewares:
    chain-google-oauth:
      chain:
        middlewares:
          - middlewares-rate-limit
          - middlewares-secure-headers
          - middlewares-oauth
          # - cloudflare
