http:
  middlewares:
    chain-google-oauth:
      chain:
        middlewares:
          - internal-cloudflare-whitelist
          - middlewares-rate-limit
          - middlewares-secure-headers
          - middlewares-oauth

    chain-github-oauth:
      chain:
        middlewares:
          - internal-cloudflare-whitelist
          - middlewares-rate-limit
          - middlewares-secure-headers
          - middlewares-oauth
