http:
  middlewares:
    # ip-whitelist:
    #   ipWhiteList:
    #     sourceRange:
    #       - 100.64.0.0/10
    #       - 192.168.0.0/16

    chain-no-auth:
      chain:
        middlewares:
          # - internal-ip-whitelist
          - internal-cloudflare-whitelist
          - middlewares-rate-limit
          - middlewares-secure-headers
