http:
  middlewares:
    chain-basic-auth:
      chain:
        middlewares:
          - internal-cloudflare-whitelist
          - middlewares-rate-limit
          - middlewares-secure-headers
          - middlewares-basic-auth
