http:
  middlewares:
    cloudflare:
      plugin:
        cloudflare:
          trustedCIDRs:
            - 100.64.0.0/10 # Cloudflare
            - 192.168.0.0/16 # internal network
            - 172.16.0.0/12 # docker network
          overwriteForwardedFor: true
